/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgproc_FrameDiff */

#ifndef _Included_imgproc_FrameDiff
#define _Included_imgproc_FrameDiff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgproc_FrameDiff
 * Method:    frameDiff
 * Signature: ([B[BII)V
 */
JNIEXPORT void JNICALL Java_imgproc_FrameDiff_frameDiff
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
