/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgproc_HomomorphicFilter */

#ifndef _Included_imgproc_HomomorphicFilter
#define _Included_imgproc_HomomorphicFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgproc_HomomorphicFilter
 * Method:    homomorphicFilter
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_imgproc_HomomorphicFilter_homomorphicFilter
  (JNIEnv *, jclass, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
