/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgproc_SkinDetect */

#ifndef _Included_imgproc_SkinDetect
#define _Included_imgproc_SkinDetect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgproc_SkinDetect
 * Method:    skinDetector1
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_imgproc_SkinDetect_skinDetector1
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     imgproc_SkinDetect
 * Method:    skinDetector2
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_imgproc_SkinDetect_skinDetector2
  (JNIEnv *, jclass, jbyteArray, jint, jint);


#ifdef __cplusplus
}
#endif
#endif
