/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class standardlibrary_GlColorSpace */

#ifndef _Included_standardlibrary_GlColorSpace
#define _Included_standardlibrary_GlColorSpace
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     standardlibrary_GlColorSpace
 * Method:    toRGB
 * Signature: (Landroid/graphics/Bitmap;[BII)V
 */
JNIEXPORT void JNICALL Java_standardlibrary_GlColorSpace_toRGB
  (JNIEnv *, jclass, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
